In [1]:
import pandas as pd
import os

In [3]:
#Making sure the program will run at the same folder the file is
os.chdir(os.getcwd())

In [ ]:
#Reading the txt file and naming the columns
Fertility_Diagnosis_set = pd.read_csv("../data/raw_fertility_Diagnosis.txt", header=None)

Fertility_Diagnosis_set.columns = ["Season", "Age", "Child Diseases", "Accident or Trauma", "Sirurgical Intervention", "High Fevers Last Year", "Frequency of Alcohool Comsumption", "Smoking Habit", "Numbers of Hours Sitting per Day", "Output"]

The definitions of the columns are:

- Season - Season in which the analysis was performed

- Age - Age at the time of analysis. Age is between 18-36 and scaled from 0 to 1

- Childish Diseases - Childish diseases i.e chicken pox, measles, mumps, polio (0: no, 1: yes)

- Accident or Trauma - Accident or serious trauma (0: no, 1: yes)

- Surgical Intervention - Surgical intervention (0: no, 1: yes)

- High Fevers Last Year - High fevers in   the last year (-1: less than 3 months ago, 0: more than 3 months ago, 1: no   fever)

- Frequency of Alcohool Comsumption - Frequency of   alcohol consumption in 5 categories scaled from 0 to 1. Following are the   categories in order: 1 several times a day, 2 every day, 3 several times a week, 4 once a week, 5 hardly ever or never

- Smoking Habit - Smoking habit (-1: never, 0: occasional, 1: daily)

- Numbers of Hours Sitting per Day - Number of hours spent sitting per day. Between 0 and 16, scaled from 0 to 1

- Output - Result of Diagnosis (N: Normal, O: Altered)

In [ ]:
Fertility_Diagnosis_set

,Season,Age,Child Diseases,Accident or Trauma,Sirurgical Intervention,High Fevers Last Year,Frequency of Alcohool Comsumption,Smoking Habit,Numbers of Hours Sitting per Day,Output
0,-0.33,0.69,0,1,1,0,0.8,0,0.88,N
1,-0.33,0.94,1,0,1,0,0.8,1,0.31,O
2,-0.33,0.50,1,0,0,0,1.0,-1,0.50,N
3,-0.33,0.75,0,1,1,0,1.0,-1,0.38,N
4,-0.33,0.67,1,1,0,0,0.8,-1,0.50,O
...,...,...,...,...,...,...,...,...,...,...
95,-1.00,0.67,1,0,0,0,1.0,-1,0.50,N
96,-1.00,0.61,1,0,0,0,0.8,0,0.50,N
97,-1.00,0.67,1,1,1,0,1.0,-1,0.31,N
98,-1.00,0.64,1,0,1,0,1.0,0,0.19,N
99,-1.00,0.69,0,1,1,0,0.6,-1,0.19,N

In [ ]:
#Replacing the numbers in season column by the actual names of the seasons
Fertility_Diagnosis_set["Season"] = Fertility_Diagnosis_set["Season"].replace({
    -0.33: "Spring",
    0.33: "Summer",
    1: "Autumn",
    -1: "Winter"
})

In [ ]:
#Saving the new file
Fertility_Diagnosis_set.to_csv("../data/Fertility_Diagnosis.csv")